### ISSUE TITLE
Synchronous callback of onreadystatechange problem

### ISSUE THREAD

**Issue by James0x57** [canjs/can-wait#41]
Hey Matthew!

This is a bit harder to explain in text than I thought it would be when I started typing... So hopefully you'll have enough info with this to remember, but if you want to pair again, just hit me up! :+1: 

Basically this line:
https://github.com/canjs/can-wait/blob/master/can-wait.js#L172
ultimately causes the resolve to fail in our setup.. Changing that to this:

```
				this.onreadystatechange = function () {
					var args = arguments;
					var self = this;
					originalSetTimeout(function () {
						callback.apply( self, args );
					}, 1);
				};
```

where 'originalSetTimeout' = setTimeout at the top of that file, it avoids the problem.

Please let me know if you need anything else or want to pair again. Thanks a ton man!
//James

**Comment by matthewp** [comment]
Yeah, so the bug is that can-wait expects its callbacks, in this case `onreadystatechange` to be called asynchronously, but in this case it was being called synchronously. Forcing it to be async fixed it.

I'm thinking the more correct fix would be for can-wait to use a variable that detects when it's being called synchronously and not call trap/release (as it has already been trapped).
